nginx:
  image: nginx:alpine
  container_name: nginx_proxy
  restart: always
  volumes:
    - ./frontend/build:/usr/share/nginx/html:ro
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt:/etc/letsencrypt:ro
  ports:
    - "80:80"
    - "443:443"
  depends_on:
    - backend
