services:
  backend:
    build: ./backend
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: react_build
    restart: "no"
    command: sleep infinity   # no runtime server, just build
    volumes:
      - frontend_build:/app/build

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  frontend_build: